AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  AWS Cloudformation template to create base resources for Querypal AWS Amplify App
Globals:
  Function:
    Timeout: 300
Parameters:
  pEnv:
    Description: The environment name
    Type: String
    Default: master
  pGitHubAccessToken:
    Description: Your github access token used to create webhook and read-only deploy key. Should be stored in SSM Parameter store
    Type: String
    NoEcho: true
  pQuerypalGitHubRepo:
    Description: Querypal GitHUb repository. Default is the OSS version. This might change if you decide customize Querypal
    Type: String
    Default: https://github.com/OElesin/querypal
  pQuerypalAppName:
    Description: Querypal AWS Amplify App Name
    Type: String
    Default: querypal
Resources:
  AmplifyDevBranch:
    Type: AWS::Amplify::Branch
    Properties:
      BranchName: !Ref pEnv
      AppId: !GetAtt QuerypalAmplifyApp.AppId
      EnableAutoBuild: yes

  QuerypalAmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: !Ref pQuerypalAppName
      Repository: !Ref pQuerypalGitHubRepo
      AccessToken: !Ref pGitHubAccessToken
      Description: Querypal - Web UI for Amazon Athena
      IAMServiceRole: !GetAtt AmplifyServiceRole.Arn
      BuildSpec: |
        version: 1
        backend:
          phases:
            preBuild:
              commands:
                - amplify --version
                - npm install -g @aws-amplify/cli
                - amplify --version
            build:
              commands:
                - '# Execute Amplify CLI with the helper script'
                - amplifyPush --simple
        frontend:
          phases:
            preBuild:
              commands:
                - yarn install
            build:
              commands:
                - yarn run build
          artifacts:
            baseDirectory: dist
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*

  AmplifyServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - amplify.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  ######## SSM #########
  AmplifyAppIdSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /Querypal/Amplify/AppID
      Type: String
      Value: !GetAtt QuerypalAmplifyApp.AppId
      Description: Querypal Amplify App Id

  ### Use AWS CloudFormation CustomResource for Amplify App Deployment ###
  DeployQueryAmplifyAppFxn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: ./function_app_deploy/
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - lambda:AddPermission
                - lambda:RemovePermission
                - events:PutRule
                - events:DeleteRule
                - events:PutTargets
                - events:RemoveTargets
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - amplify:GetApp
                - amplify:GetBranch
                - amplify:UpdateApp
                - amplify:UpdateBranch
                - amplify:StartJob
                - amplify:GetJob
                - amplify:StopJob
                - amplify:DeleteApp
              Resource: '*'

  DeployQueryAmplifyApp:
    Type: Custom::DeployAmplifyApp
    DependsOn:
      - AmplifyDevBranch
    Properties:
      ServiceToken: !GetAtt DeployQueryAmplifyAppFxn.Arn
      AmplifyAppId: !GetAtt QuerypalAmplifyApp.AppId
      BranchName: !Ref pEnv

Outputs:
  QuerypalAmplifyDomain:
    Value: !Sub 'https://${pEnv}.${QuerypalAmplifyApp.DefaultDomain}'
  QuerypalAmplifyAppId:
    Value: !GetAtt QuerypalAmplifyApp.AppId
